steps:
  # Build the Docker image with all environment variables
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'VITE_FIREBASE_API_KEY=${_FIREBASE_API_KEY}'
      - '--build-arg'
      - 'VITE_FIREBASE_AUTH_DOMAIN=${_AUTH_DOMAIN}'
      - '--build-arg'
      - 'VITE_FIREBASE_PROJECT_ID=${_PROJECT_ID}'
      - '--build-arg'
      - 'VITE_FIREBASE_STORAGE_BUCKET=${_STORAGE_BUCKET}'
      - '--build-arg'
      - 'VITE_FIREBASE_MESSAGING_SENDER_ID=${_MESSAGING_SENDER_ID}'
      - '--build-arg'
      - 'VITE_FIREBASE_APP_ID=${_APP_ID}'
      - '--build-arg'
      - 'VITE_FIREBASE_MEASUREMENT_ID=${_MEASUREMENT_ID}'
      - '--build-arg'
      - 'VITE_GEMINI_API_KEY=${_GEMINI_API_KEY}'
      - '--build-arg'
      - 'VITE_YOUTUBE_API_KEY=${_YOUTUBE_API_KEY}'
      - '--build-arg'
      - 'VITE_QUOTE_API=${_QUOTE_API}'
      - '--build-arg'
      - 'VITE_MEME_API=${_MEME_API}'
      - '--build-arg'
      - 'VITE_API_BASE_URL=${_API_BASE_URL}'
      - '--build-arg'
      - 'VITE_USE_BACKEND_API=${_USE_BACKEND_API}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/mintai-app:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/mintai-app:latest'
      - '.'
    id: 'build-image'

  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mintai-app:$BUILD_ID']
    id: 'push-image-buildid'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mintai-app:latest']
    id: 'push-image-latest'

# Substitutions with default values (override these when calling)
# Note: Leave empty and pass via command line for security
substitutions:
  _FIREBASE_API_KEY: ''
  _AUTH_DOMAIN: ''
  _PROJECT_ID: ''
  _STORAGE_BUCKET: ''
  _MESSAGING_SENDER_ID: ''
  _APP_ID: ''
  _MEASUREMENT_ID: ''
  _GEMINI_API_KEY: ''
  _YOUTUBE_API_KEY: ''
  _QUOTE_API: ''
  _MEME_API: ''
  _API_BASE_URL: ''
  _USE_BACKEND_API: 'false'
  
# IMPORTANT: Pass substitutions via command line:
# gcloud builds submit --config cloudbuild.yaml --substitutions _FIREBASE_API_KEY="...",...

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'gcr.io/$PROJECT_ID/mintai-app:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/mintai-app:latest'

